In [1]:
import pandas as pd
import numpy as np

In [40]:
#word counts per doc
X = np.array([[0,4,3],[3,2,2], [2,1,3],[1,2,2],[2,1,1]])

In [204]:
p = X.shape[1] ;p #number of unique features/words

3

In [216]:
alpha = 1

In [41]:
X

array([[0, 4, 3],
       [3, 2, 2],
       [2, 1, 3],
       [1, 2, 2],
       [2, 1, 1]])

In [62]:
y = np.array([1,0,0,1,1]) #class values

In [207]:
y = y.astype(bool) ;y

array([ True, False, False,  True,  True])

In [205]:
#  [X.sum(axis=0) where y == True]

SyntaxError: invalid syntax (<ipython-input-205-2124c56d4387>, line 1)

In [239]:
len(y[y ==True])

3

In [242]:
np.array((len(y[y == True]), len(y[y == False]))) / len(y)

array([0.6, 0.4])

In [236]:
spam_word_sum = np.sum(X, axis=0)
spam_word_sum
#summing each word over all docs for SPAM

array([ 8, 10, 11])

In [233]:
not_spam_word_sum = np.sum(X[~y], axis=0) #summing each word over all docs for NOT SPAM

In [210]:
X

array([[0, 4, 3],
       [3, 2, 2],
       [2, 1, 3],
       [1, 2, 2],
       [2, 1, 1]])

In [212]:
y.astype(int)

array([1, 0, 0, 1, 1])

In [89]:
X_spam = np.sum(X[y, :], axis=0)

array([3, 7, 6])

In [213]:
X_spam_not = np.sum(X[~y, :], axis=0); X_spam_not

array([5, 3, 5])

In [208]:
#np.dot(X.sum(axis=0), np.sum(X[y, :], axis=0))

In [209]:
# np.dot((np.array((X_spam, X_spam_not))), X.sum(axis=0))

In [202]:
class_feature_counts = np.array((X_spam, X_spam_not)) ;class_feature_counts

array([[3, 7, 6],
       [5, 3, 5]])

In [215]:
#Nj
class_total_feature_counts = np.sum(new_array, axis=1) 
class_total_feature_counts


array([16, 13])

In [243]:
log_likelilhood = np.log((alpha + class_feature_counts.T)/(alpha*p + class_total_feature_counts))
log_likelilhood
# True form of New_array

array([[-1.55814462, -0.98082925],
       [-0.86499744, -1.38629436],
       [-0.99852883, -0.98082925]])

In [226]:
summation = np.dot(X, log_likelilhood) ; summation

array([[-6.45557624, -8.4876652 ],
       [-8.40148639, -7.67673499],
       [-6.97687316, -6.29044063],
       [-5.28519715, -5.71507648],
       [-4.9798155 , -4.32878212]])

In [299]:
test = np.array([['fishing'],['not'],['fishing']])

In [300]:
v1 = np.unique(test)[0]
v2 = np.unique(test)[1]

In [301]:
test[np.where(test == v1)] = 0
test[np.where(test == v2)] = 1

In [304]:
test = test.astype(bool)

In [305]:
test

array([[False],
       [ True],
       [False]])

In [306]:
books = np.array([['a', 'long', 'fishing', 'document', 'about', 'fishing'], ['a', 'book', 'on', 'fishing'], ['a', 'book', 'on', 'knot-tying']])

In [ ]:
>>> n = 43365644
>>> [int(d) for d in str(n)]
[4, 3, 3, 6, 5, 6, 4, 4]

In [332]:
cats = np.array(['0' '0' '1'])
cats = [d for d in str(cats)]


SyntaxError: can't assign to function call (<ipython-input-332-7b84aa227fca>, line 2)

In [329]:
cats

['001']

In [266]:
ytest = np.array([0,1])

In [267]:
test[ytest]

array([['fishing'],
       ['not']], dtype='<U7')

In [235]:
prior = np.array((spam, not_spam)) ; prior

array([0.6, 0.4])

In [237]:
probability_per_document = summation + np.log(prior)
probability_per_document

array([[-6.96640186, -9.40395594],
       [-8.91231201, -8.59302572],
       [-7.48769879, -7.20673136],
       [-5.79602278, -6.63136721],
       [-5.49064113, -5.24507285]])

In [219]:
class_feature_counts

array([[3, 7, 6],
       [5, 3, 5]])

In [220]:
class_total_feature_counts

array([16, 13])

In [141]:
X

array([[0, 4, 3],
       [3, 2, 2],
       [2, 1, 3],
       [1, 2, 2],
       [2, 1, 1]])

In [142]:
new_array

array([[3, 7, 6],
       [5, 3, 5]])

In [164]:
summation = np.dot(X, new_array.T) ; summation

array([[46, 27],
       [35, 31],
       [31, 28],
       [29, 21],
       [19, 18]])

In [136]:
np.dot((X, np.array((X_spam, X_spam_not))))

TypeError: Required argument 'b' (pos 2) not found

In [126]:
(np.array((X_spam, X_spam_not)))

array([[3, 7, 6],
       [5, 3, 5]])

In [144]:
X

array([[0, 4, 3],
       [3, 2, 2],
       [2, 1, 3],
       [1, 2, 2],
       [2, 1, 1]])

In [145]:
y

array([ True, False, False,  True,  True])

In [148]:
X[y]

array([[0, 4, 3],
       [1, 2, 2],
       [2, 1, 1]])

In [193]:
spam = len(y[y==True]) / len(y) ; spam

0.6

In [194]:
not_spam = len(y[y==False]) / len(y) ; not_spam

0.4

In [196]:
prior = np.array((spam, not_spam)) ; prior

array([0.6, 0.4])

In [167]:
summation

array([[46, 27],
       [35, 31],
       [31, 28],
       [29, 21],
       [19, 18]])

In [198]:
prior + summation

array([[46.6, 27.4],
       [35.6, 31.4],
       [31.6, 28.4],
       [29.6, 21.4],
       [19.6, 18.4]])

In [157]:
spam_sum

array([0.10344828, 0.24137931, 0.20689655])

In [158]:
not_spam_sum

array([0.17241379, 0.10344828, 0.17241379])