In [1]:
import numpy as np

In [3]:
a = np.arange(25).reshape(5,5)

In [4]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
a[:,1::2]
a[4,:]
a[1::2, :3:2]

array([[ 5,  7],
       [15, 17]])

In [52]:
mask = a >10
a[mask]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

Write a function that creates a column vector (an array of shape (1, n)) containing the sequence of numbers 0, 1, 2, ..., n-1:

In [53]:
def column_vector(n):
    return np.arange(n)
column_vector(3)

array([0, 1, 2])

Write a function that creates an array of random floating point numbers between zero and one of a given shape:

In [ ]:
def random_array(r,c):
    return np.random.rand(r,c)
random_array(4,3)

Given an integer numpy array of 0's and 1's, write a function that creates a new array where 0's are replaced with the word "red" and 1's are replaced with the word "blue".

In [98]:
x = np.array([0, 0, 1, 0, 1],dtype=bool) 
def color_replace(x):
    y = []
    for i in range(len(x)):
        if i == True:
            y.append('red')
        else:
            y.append('blue')
    return y
color_replace(x)

['blue', 'red', 'blue', 'blue', 'blue']

Given two equal length arrays, x with some general numeric data, and b an array of booleans, write a function that computes the sum of the data in x at the same positions where b is True, and the sum of the values in x at the positions where b is false.